### ISSUE TITLE
Remaining task checklist

### ISSUE THREAD

**Issue by nicktaras** [TokenScript/token-negotiator#56]
List of tasks to complete Token-Negotiator (Client Side Demo and Package)

- [ ] Create a Devcon account management page (showing use of tokens inside Devcon website example)

 | Page should show tickets loading into view when enabled.

- [ ] Responsive Styling (ensure the modal can be viewed in mobile device widths e.g. Iphone5-X)

- [ ] Split the Negotiator Code into Client, Modal, Core logic (responsbilities).

- [ ] Safari Fix (change event dispatching method used)

- [ ] Unit Tests

- [ ] Update Readme

- [ ] White List Functionality

- [ ] Move Signed Devcon Ticket (can discuss this, however this will enable the lib to better scale)

- [ ] Switch out any T-N code naming to Token /rather than Ticket or anything containing Devcon

- [ ] Github actions when the unit tests are done to stop merges before code is of a specific quality

- [ ] Deploy NPM to @tokenscript

- [ ] Update Readme, Demo notes

- [ ] Development testing across devices / fixes / updates

- [ ] Align Webpack build script / Typescript configs

- [ ] Move Demo examples into seperate repository (as discussed in last weeks meeting with Weiwu)

**Comment by nicktaras** [comment]
Examples from 'main' migrated to https://github.com/TokenScript/token-negotiator-examples/settings

Tested and working as per Demo with Devcon.

**Comment by jot2re** [comment]
@nicktaras Gradle issue fixed, but pushing  version 0.1.4 directly from main (since now the Maven issuance branch has been merged)
